create table person (id bigint generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table roles (id bigint not null, name varchar(255) not null check (name in ('ADMIN','USER')));
alter table if exists roles add constraint FKcisfsddceww3xlf4d1btfv845 foreign key (id) references person;
